# 端口
server:
  port: 7000
  tomcat:
    uri-encoding: UTF-8
    basedir: /Users/liugf
    max-threads: 2000
    min-spare-threads: 10
    accesslog:
      pattern: common
      enabled: true
      directory: logs
      prefix: access_log
      suffix: .log
      request-attributes-enabled: true
      rename-on-rotate: true
    max-swallow-size: -1
  servlet:
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
spring:
  application:
    name: system-monitor
  #json 时间戳统一转换
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
  # 接口安全验证
  security:
    user:
      name: parker
      password: NET!@0p9o8i7u